version: "3.8"

services:
  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: always
    ports:
      - 7000:1080 # ui port

  minio:
    image: minio/minio
    container_name: minio
    command: server /data/minio/ --console-address :9001
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 7001:9001 # ui port

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=directus
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  redisinsight:
    image: redis/redisinsight
    container_name: redisinsight
    restart: always
    ports:
      - 7002:5540

volumes:
  db_data:
