version: "3.8"

services:
  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: always
    ports:
      - 1080:1080 # ui port
      - 1025:1025

  minio:
    image: minio/minio
    container_name: minio
    command: server /data/minio/ --console-address :9001
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9001:9001 # ui port
      - 9000:9000

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=directus
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 6379:6379

  redisinsight:
    image: redis/redisinsight
    container_name: redisinsight
    restart: always
    ports:
      - 5540:5540 # ui port

volumes:
  db_data:
